version: '3'

volumes:
  ollama_storage:
  open-webui:
  n8n_storage:
  qdrant_storage:
  flowise:

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - ollama_storage:/root/.ollama
      - ./Modelfile:/Modelfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_INSECURE=true
      - OLLAMA_SKIP_CERT_VERIFY=true
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*

  ollama-pull-models:
    image: ollama/ollama:latest
    container_name: ollama-pull-models
    volumes:
      - ollama_storage:/root/.ollama
    entrypoint: /bin/sh
    command:
      - "-c"
      - "sleep 10 && OLLAMA_HOST=ollama:11434 ollama pull mistral && OLLAMA_HOST=ollama:11434 ollama pull nomic-embed-text && OLLAMA_HOST=ollama:11434 ollama pull dolphin-mixtral:8x7b && OLLAMA_HOST=ollama:11434 ollama pull mxbai-embed-large:335m && OLLAMA_HOST=ollama:11434 ollama pull nidumai/nidum-gemma-3-4b-it-uncensored:q3_k_m"
    depends_on:
      - ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
      - ollama-pull-models
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'OLLAMA_INSECURE=true'
      - 'OLLAMA_SKIP_CERT_VERIFY=true'
      - 'NODE_TLS_REJECT_UNAUTHORIZED=0'
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - DB_TYPE=sqlite
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ENCRYPTION_KEY=12345678901234567890123456789012
      - N8N_USER_MANAGEMENT_JWT_SECRET=jwtSecret
      - N8N_SECURE_COOKIE=FALSE
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./shared:/data/shared

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage
      
  flowise:
    image: flowiseai/flowise
    restart: unless-stopped
    container_name: flowise
    environment:
        - PORT=3001
    ports:
        - 3001:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"        
    volumes:
        - flowise:/root/.flowise
    entrypoint: /bin/sh -c "sleep 3; flowise start" 